apiVersion: apps/v1

kind: Deployment

metadata:
  name: bgg-db-deployment
  namespace: workshops02

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bgg-db-pod

  template:
    metadata:
      name: bgg-db-pod
      labels: 
        app.kubernetes.io/name: bgg-db-pod
        app.kubernetes.io/version: "v1"
        owner: engineering

    spec:
      containers:
      - name: fortune
        image: stackupiss/bgg-db:v1
        imagePullPolicy: Always
        env:
        - name: mysql-port
          value: "3006"
        ports:
        - name: fortune-port
          containerPort: 3000


---

apiVersion: v1
kind: Service

metadata:
  name: bgg-db-svc
  namespace: workshops02
  metadata:
  labels:
    name: bgg-db-svc

spec:
  type: ClusterIP
  selector: 
    app.kubernetes.io/name: bgg-db-pod

  ports:
  - name: mysql-port-svc
    port: 3306
    targetPort: mysql-port